parent_cfg: configs/mvsgs/tnt_eval.yaml
exp_name: tnt_ft_horse
mvsgs:
    test_input_views: 4
    train_input_views: [3, 4]
    train_input_views_prob: [0.4, 0.6]
    cas_config:
        render_if: [True, True]
train_dataset:
    scene: Horse
test_dataset:
    scene: Horse
train:
    epoch: 233 # pretrained epoch +10
    lr: 5e-5
save_ep: 1
eval_ep: 1
