parent_cfg: configs/mvsgs/dtu_pretrain.yaml

train_dataset_module: lib.datasets.mipnerf.mvsgs
test_dataset_module: lib.datasets.mipnerf.mvsgs

mvsgs:
    eval_center: True
    reweighting: True
    scale_factor: 1
    cas_config:
        render_if: [False, True]
        volume_planes: [512, 32]

train_dataset:
    data_root: '../../data/nerf_mipnerf_data'
    split: 'train'
    input_h_w: [640, 960]
    input_ratio: 1.

test_dataset:
    data_root: '../../data/nerf_mipnerf_data'
    split: 'test'
    input_h_w: [640, 960]
    input_ratio: 1.
